import { useMemo, useState } from 'react';
import { VscChromeClose, VscSearch } from "react-icons/vsc";
import jsPDF from "jspdf";
import AdminProfile from '../../../hooks/AdminHooks/AdminProfile.js';

const TotalGowns = ({ setTotalReserve, DashInfo }) => {
  const [searchQuery, setSearchQuery] = useState('');
  const {profile} = AdminProfile();
  // Group items by product name and merge their sizes
  const mergedGowns = useMemo(() => {
    const groupedItems = DashInfo.reduce((acc, item) => {
      const key = `${item.product_Name}-${item.type}-${item.gender}-${item.price}`;
      
      if (!acc[key]) {
        acc[key] = {
          ...item,
          allSizes: new Set([item.sizes]),
          totalQuantity: item.quantity,
          sizeQuantities: {
            [item.sizes]: item.quantity
          }
        };
      } else {
        acc[key].allSizes.add(item.sizes);
        acc[key].totalQuantity += item.quantity;
        acc[key].sizeQuantities[item.sizes] = item.quantity;
      }
      return acc;
    }, {});

    return Object.values(groupedItems).map(item => ({
      ...item,
      allSizes: Array.from(item.allSizes).sort()
    }));
  }, [DashInfo]);

  // Filter gowns based on search query
  const filteredGowns = useMemo(() => {
    return mergedGowns.filter(item =>
      item.product_Name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.type.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.gender.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }, [mergedGowns, searchQuery]);

 

  const generatePDF = () => {
    // Initialize PDF document
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    let yPosition = 20;
  
    // Helper functions
    const checkPageBreak = (requiredSpace) => {
      if (yPosition + requiredSpace >= 280) {
        doc.addPage();
        yPosition = 20;
        return true;
      }
      return false;
    };
  
    const addCenteredText = (text, y, fontSize = 12) => {
      doc.setFontSize(fontSize);
      const textWidth = doc.getStringUnitWidth(text) * fontSize / doc.internal.scaleFactor;
      const textOffset = (pageWidth - textWidth) / 2;
      doc.text(text, textOffset, y);
    };
  
    // Header with professional styling
    doc.setFillColor(147, 112, 219); // Purple theme for fashion
    doc.rect(0, 0, pageWidth, 15, 'F');
    
    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    addCenteredText('Gowns Inventory Report', 10);
    
    // Reset text color
    doc.setTextColor(0, 0, 0);
    
    // Report metadata
    yPosition += 15;
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    const currentDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
    const currentTime = new Date().toLocaleTimeString('en-US', {
      hour: '2-digit',
      minute: '2-digit'
    });
    
    doc.text(`Generated on: ${currentDate} at ${currentTime}`, 10, yPosition);
    yPosition += 7;
    doc.text(`Generated by: ${profile[0].name}`, 10, yPosition);
  
    // Summary section with styled box
    yPosition += 15;
    const totalGowns = filteredGowns.length;
    const totalValue = filteredGowns.reduce((sum, gown) => sum + (gown.price * gown.totalQuantity), 0);
  
    doc.setFillColor(247, 240, 255);
    doc.setDrawColor(147, 112, 219);
    doc.roundedRect(10, yPosition, pageWidth - 20, 35, 3, 3, 'FD');
    
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Inventory Summary', 15, yPosition + 7);
    
    doc.setFontSize(12);
    doc.setFont(undefined, 'normal');
    doc.text(`Total Gowns: ${totalGowns} styles`, 20, yPosition + 20);
    doc.text(`Total Inventory Value: ₱${totalValue.toLocaleString()}`, 20, yPosition + 30);
  
    // Gown Details Section
    yPosition += 45;
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Detailed Inventory', 10, yPosition);
    
    // Add decorative line
    yPosition += 3;
    doc.setDrawColor(147, 112, 219);
    doc.setLineWidth(0.5);
    doc.line(10, yPosition, pageWidth - 10, yPosition);
  
    // Individual Gown Details
    filteredGowns.forEach((gown, index) => {
      yPosition += 15;
      checkPageBreak(100); // Estimated space needed for each gown
  
      // Gown header with styled background
      doc.setFillColor(247, 240, 255);
      doc.roundedRect(10, yPosition - 5, pageWidth - 20, 12, 2, 2, 'F');
      
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text(`${index + 1}. ${gown.product_Name}`, 15, yPosition + 2);
      doc.setFont(undefined, 'normal');
      doc.text(`ID: ${gown.id}`, pageWidth - 50, yPosition + 2);
  
      // Basic details in two columns
      yPosition += 15;
      // Left column
      doc.text(`Type: ${gown.type}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Gender: ${gown.gender}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Material: ${gown.material}`, 20, yPosition);
      
      // Right column
      doc.text(`Color: ${gown.color}`, pageWidth/2, yPosition - 14);
      doc.text(`Price: ₱${gown.price.toLocaleString()}`, pageWidth/2, yPosition - 7);
      doc.text(`Total Quantity: ${gown.totalQuantity} pieces`, pageWidth/2, yPosition);
  
      // Size information in a grid
      yPosition += 15;
      doc.setFont(undefined, 'bold');
      doc.text('Size Distribution:', 20, yPosition);
      doc.setFont(undefined, 'normal');
      
      yPosition += 7;
      const sizeEntries = Object.entries(gown.sizeQuantities);
      let currentX = 25;
      sizeEntries.forEach(([size, quantity]) => {
        doc.text(`${size}: ${quantity}`, currentX, yPosition);
        currentX += 35;
      });
  
      // Description with word wrap
      yPosition += 15;
      doc.setFont(undefined, 'bold');
      doc.text('Description:', 20, yPosition);
      doc.setFont(undefined, 'normal');
      const splitDescription = doc.splitTextToSize(gown.description, pageWidth - 40);
      yPosition += 7;
      doc.text(splitDescription, 20, yPosition);
      yPosition += (splitDescription.length * 7);
  
      // Separator
      yPosition += 5;
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.2);
      doc.line(15, yPosition, pageWidth - 15, yPosition);
    });
  
    // Footer with page numbers
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      addCenteredText(`Page ${i} of ${totalPages}`, 290);
    }
  
    // Save the PDF
    doc.save('gowns-inventory-report.pdf');
  };



  return (
    <div className="fixed inset-0 flex items-center justify-center z-50">
      {/* Backdrop with stronger blur effect */}
      <div 
        className="absolute inset-0 bg-black/50 backdrop-blur-md"
        onClick={() => setTotalReserve(prev => ({ ...prev, TotalGowns: false }))}
      />
      
      {/* Modal Container */}
      <div className="relative w-full max-w-7xl mx-4 bg-white/90 backdrop-blur-sm rounded-2xl shadow-2xl border border-white/20">
        {/* Header */}
        <div className="flex flex-col gap-4 p-6 border-b border-gray-200/50">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-semibold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">Total Gowns</h2>
            <button
              onClick={() => setTotalReserve(prev => ({ ...prev, TotalGowns: false }))}
              className="p-2 rounded-full hover:bg-gray-100/50 transition-colors"
            >
              <VscChromeClose className="w-5 h-5 text-gray-500" />
            </button>
          </div>
          
          {/* Search Bar */}
          <div className="relative">
            <VscSearch className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <input
              type="text"
              placeholder="Search by name, type, or gender..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-10 pr-4 py-2 rounded-lg bg-white/50 backdrop-blur-sm border border-gray-200/50 focus:outline-none focus:ring-2 focus:ring-blue-500/20 transition-all"
            />
          </div>
        </div>
      

        <div className='ml-7'>
     <button
              onClick={generatePDF}
              className="
                px-5 py-1 rounded-lg
                bg-gradient-to-r from-blue-500 to-purple-500
                text-white font-medium
                hover:shadow-lg hover:shadow-blue-500/25
                transition-all duration-200
                flex items-center gap-2
              "
            >
              Print Report
            </button>
     </div>

        {/* Scrollable Content Area */}
        <div className="overflow-y-auto h-[calc(100vh-15rem)]">
          <div className="p-6">
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
              {filteredGowns.map((item, index) => (
                <div
                  key={index}
                  className="group bg-white/80 backdrop-blur-sm rounded-xl border border-gray-200/50 overflow-hidden hover:shadow-lg hover:scale-105 transition-all duration-300"
                >
                  {/* Image Section */}
                  <div className="aspect-square w-full overflow-hidden relative">
                    <img
                      src={`http://localhost:8000//uploads/${item.image}`}
                      alt={item.product_Name}
                      className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500"
                    />
                    <div className="absolute top-2 right-2">
                      <span
                        className={`text-xs px-2 py-1 rounded-full font-medium ${
                          item.totalQuantity === 0
                            ? "bg-red-100/90 text-red-600"
                            : "bg-green-100/90 text-green-600"
                        }`}
                      >
                        Total: {item.totalQuantity}
                      </span>
                    </div>
                  </div>

                  {/* Content Section */}
                  <div className="p-3 space-y-2">
                    <div>
                      <h3 className="font-medium text-gray-900 truncate">
                        {item.product_Name}
                      </h3>
                      <p className="text-xs text-gray-500">₱{item.price}</p>
                    </div>

                    {/* Size Pills with Quantities */}
                    <div className="flex flex-wrap gap-1">
                      {item.allSizes.map((size, sizeIndex) => (
                        <div
                          key={sizeIndex}
                          className="px-2 py-0.5 text-xs rounded-full bg-gray-100/70 text-gray-700 flex items-center gap-1"
                        >
                          <span>{size}</span>
                          <span className="inline-flex items-center justify-center bg-gray-200/70 rounded-full w-4 h-4 text-[10px]">
                            {item.sizeQuantities[size]}
                          </span>
                        </div>
                      ))}
                    </div>

                    <div className="flex justify-between items-center text-xs text-gray-600">
                      <span className="bg-gray-100/70 px-2 py-0.5 rounded-full">{item.type}</span>
                      <span className="bg-gray-100/70 px-2 py-0.5 rounded-full">{item.gender}</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TotalGowns;